WebBanSmartphones/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanSmartphones.Context;
using WebBanSmartphones.Models;
namespace WebBanSmartphones.Controllers
{
    public class CartController : Controller
    {
        WebSiteBanHangEntities objWebSiteBanHangEntities = new WebSiteBanHangEntities();

        // GET: Card
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objWebSiteBanHangEntities.Product_2119110227.Find(id), Quantity = quantity});
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
               List<CartModel> cart = (List<CartModel>)Session["cart"];

               int index = isExist(id);
               if(index != -1)
               {
                    cart[index].Quantity += quantity;
               }
               else
               {
                    cart.Add(new CartModel {Product = objWebSiteBanHangEntities.Product_2119110227.Find(id), Quantity = quantity});

                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
               }
                Session["cart"] = cart;
            }
            return Json(new { Massage = "Thành Công", JsonRequestBehavior.AllowGet });
         }
         private int isExist(int id)
         {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.Id.Equals(id))
                    return i;
            return -1;
         }
        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.Id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

WebBanSmartphones/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanSmartphones.Context;
using WebBanSmartphones.Models;

namespace WebBanSmartphones.Controllers
{

    public class PaymentController : Controller
    {
        WebSiteBanHangEntities objWebSiteBanHangEntities = new WebSiteBanHangEntities();

        // GET: Payment
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                // lay tt tu gio hang tu bien session
                var lstCart = (List<CartModel>)Session["cart"];
                // gan du lieu cho order
                Order_2119110227 objOrder = new Order_2119110227();
                objOrder.Name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objOrder.UserId = int.Parse(Session["idUser"].ToString());
                objOrder.CreatedOnUtc = DateTime.Now;
                objOrder.Status = 1;
                objWebSiteBanHangEntities.Order_2119110227.Add(objOrder);

                objWebSiteBanHangEntities.SaveChanges();

                int intOrderId = objOrder.Id;
                List<OrderDetail_2119110227> lstOrderDetail = new List<OrderDetail_2119110227>();

                foreach(var item in lstCart)
                {
                    OrderDetail_2119110227 obj = new OrderDetail_2119110227();
                    obj.Quantity = item.Quantity;
                    obj.OrderId = intOrderId;
                    obj.ProductId = item.Product.Id;
                    lstOrderDetail.Add(obj);
                }
                objWebSiteBanHangEntities.OrderDetail_2119110227.AddRange(lstOrderDetail);
                objWebSiteBanHangEntities.SaveChanges();

            }
            return View();
        }
    }
}

WebBanSmartphones/Views/Cart/Index.cshtml
@model IEnumerable<WebBanSmartphones.Models.CartModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="~/Content/js/main.js"></script>
<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $( "#product-" +   model.Id ).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>
<!-- ========================= SECTION CONTENT ========================= -->
@{ decimal thanhtien = 0;}
<section class="section-content padding-y">
    <div class="container">

        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted text-center">
                            <tr class="small text-uppercase">
                                <th scope="col">Sản phẩm</th>
                                <th scope="col" width="120">Số lượng</th>
                                <th scope="col" width="120">Giá</th>
                                <th scope="col" width="120">Thành tiền</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    var price = item.Product.Price;
                                    var priceSale = item.Product.PriceDiscouunt;
                                    var quatity = item.Quantity;
                                    thanhtien += (Convert.ToDecimal(priceSale * quatity));


                                    <tr>
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.Avatar" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.Name </a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            @*<input type="text" value="@item.Quantity" />*@
                                            <label>@item.Quantity</label>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                @if (item.Product.PriceDiscouunt != null)
                                                {

                                                    <var class="price">@Convert.ToDecimal(priceSale).ToString("#,##0")<sup>đ</sup></var>
                                                }
                                                else
                                                {

                                                    <var class="price">@Convert.ToDecimal(price).ToString("#,##0")<sup>đ</sup></var>
                                                }
                                                @*<small class="text-muted"> $578.00 each</small>*@
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td>
                                            <!--Thành tiền-->
                                            <div class="price-wrap">
                                                <var class="price">@Convert.ToDecimal(priceSale * quatity).ToString("#,##0")<sup>đ</sup></var>

                                                @*<small class="text-muted"> $578.00 each</small>*@
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.Id" id="productid" />
                                            <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>
                                            <a href="" class="btn btn-light" id="removecart"> Xóa</a>
                                        </td>
                                    </tr>
                                }

                            }
                            else
                            {

                                <p style="color:dimgray; font-size:25px;font-weight:bold; margin-left:60px; margin-top:30px; ">Giỏ hàng trống</p>
                            }
                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        @if (Session["cart"] != null)
                        {

                            <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right"> Thanh toán <i class="fa fa-chevron-right"></i> </a>
                        }
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Tiếp tục mua sắm </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Giao hàng miễn phí trong vòng 1-2 ngày</p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Phiếu giảm giá <span style="color:dimgray;">(Nếu có)</span></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Mã giảm giá">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Áp dụng</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card">
                    <div class="card-body">




                        <dl class="dlist-align">
                            <dt>Số sản phẩm:</dt>
                            @if (@Session["count"] != null)
                            {
                                <dd class="text-right">@Session["count"]</dd>
                            }
                            else
                            {
                                <dd class="text-right"></dd>

                            }


                        </dl>
                        @*<dl class="dlist-align">
                                <dt>Discount:</dt>
                                <dd class="text-right">USD 658</dd>
                            </dl>*@


                        <dl class="dlist-align">
                            <dt>Tổng tiền:</dt>
                            <dd class="text-right  h5"><strong>@(Convert.ToDecimal(thanhtien).ToString("#,##0"))<sup>đ</sup></strong></dd>
                        </dl>

                        <hr>
                        <p class="text-center mb-3">
                            <img src="~/Content/images/misc/payments.png" height="26">
                        </p>

                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->